title: 🤖 AI Robotics Portfolio
description: ROS2 • Docker • Linux • Python • Machine Learning • Robotics

theme: jekyll-theme-cayman

show_downloads: false

github:
  is_project_page: true

plugins:
  - jekyll-seo-tag

lang: zh-CN
